name: Auto Inference on Commit
run-name: Testing inference...
on: workflow_dispatch
jobs:
  inference-test-job:
    runs-on: ubuntu-latest
    container: hi94740/bio-trophy-so-vits-inf
    steps: 
      - name: Run inference
        run: python inference_main.py -n test.wav -m /app/models/Faruzan/G.pth -s Faruzan -t 0 -cr 0 -c /app/models/Faruzan/config.json -cm /app/models/Faruzan/kmeans.pt -sd -40 -wf flac --f0_predictor=crepe