name: Auto Inference on Commit
run-name: Testing inference...
on: workflow_dispatch
jobs:
  inference-test-job:
    runs-on: ubuntu-latest
    container: 
      image: hi94740/bio-trophy-so-vits-inf
      options: --user root
    steps: 
      - uses: actions/checkout@v3
        with: 
          path: ssml
      - name: Move Ssml Folder
        run: mv $GITHUB_WORKSPACE/ssml /ssml
      - name: Run inference
        run: node /app/dist/index.js